### ISSUE TITLE
Revisit the 3-tab design in CB steps

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/iguide-circuit-breaker#117]
For the circuit-breaker guide, revisit the 3-tab design to understand how the "code" column (the far right column) should appear.

8/6: Meeting with Design.  Denise, Megan, Jay, Kevin, Steven, Erica attended.

Questions/Concerns: 
- The design indicates that once a step is "complete", the down arrow hint appears.   This behavior is different from the static guides, where the down arrow only appears at the bottom of the first page.  Which way should we implement? 
    - Mtg 8/6 -> enable down arrow for each page (section) when all instructions are complete.  This may be slightly different in the CB guide since the playground 'Configure it' steps should not be required.
- Overly complicated for the dual pane design
  - Will lose some text information that previously appeared in the 2nd "tab" when the step playground overlays that part of the screen.
       - Mtg 8/6 -> Move some of the text in the result pane to the instructions so that the data is not lost.
  - The playground on the 'Configuring' steps should be optional.

     - Mtg 8/6 -> Add text to the last instruction for 'Configure it' to indicate that this step is optional. (Issue #127)

- As you scroll through the guide, do the parts on the right keep changing based on which page's section holds the majority of the text column?
     - - Mtg 8/6 -> Yes.   Section snapping will take the user to the top of the section that controls most of the screen height.
- Can we have a scroll bar for the results section, the browser, **and** the guide at the same time?  Is that ok?
     - - Mtg 8/6 -> YES....it will have to be, but try to minimize it.

- What to do when going back to mobile view (single column).  Do we hold the current browser, results, and editor state and swap them inline?  Where do they appear?  Under all the instructions, even if it means lots of scrolling?  Previously we only showed the current instruction so there was less scrolling down in a single-column view to get to the page's widgets.
     - - Mtg 8/6 - We want to replicate the way the guide works today when we go to a single column view.  We will need to swap in the browser and editor widgets to their appropriate spot so that they do not lose state.   They will appear as they do today in single column view under the last instruction being worked on. Incomplete instructions will be hidden in single column view (except for the one currently being worked on).  See https://github.com/OpenLiberty/iguides-common/issues/164.

**Comment by dmorgant** [comment]
All issues above have been handled as indicated. Closing this "catch all" issue.
