### ISSUE TITLE
Playground: Brackets [ and ] disappear

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/iguide-circuit-breaker#118]
Step:
https://openliberty.io/guides/circuit-breaker.html#configuring-the-success-threshold

Objective:
The square brackets representing the rolling window disappear after awhile.

Recreate:
1.  Use default values in the editor
2.  Click one failure and one success
3.  Observe the picture below.  The brackets never reappear.

![image](https://user-images.githubusercontent.com/31117513/41300749-17d16672-6e2c-11e8-9806-322703f8900e.png)

**Comment by steven1046** [comment]
@kinueng the concept of the rolling window (the brackets) is only related to the Closed circuit state, because the percentage of failures in the rolling window determines when the circuit will open.

**Comment by steven1046** [comment]
Todo: clarify in all of the circuit breaker playgrounds when the rolling window concept is used and when it is not.

**Comment by amyreit** [comment]
Modifying the sentence  to - The brackets represent the rolling window **when the circuit is closed.**
