### ISSUE TITLE
playground: remove the save instruction, instead use auto-save

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/iguide-circuit-breaker#13]
Options to do that:
- add a listener in editor to listen to content changes
- every time a success/failure button is clicked, check the content of the editor

**Comment by lavenal** [comment]
PR #31

**Comment by steven1046** [comment]
The auto save is complete by Lavena in #31, but we still need to parse the editor for to see if they haven't supplied any of the four parameters, which will use the default values.
