### ISSUE TITLE
Update the Global ebank web site with new opening page design.

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguide-circuit-breaker#150]
Refer to Megan's new Global ebank web site design in the ac-guides-design channel and update our html to look like that.   There is also information in the slack channel on the interaction and possible changing of the instruction text.

Update to circuit-breaker-welcome.html.

**Comment by kinueng** [comment]
We need SVG images from design

**Comment by kinueng** [comment]
![image](https://user-images.githubusercontent.com/31117513/46485987-6d87cf80-c7c2-11e8-8f9c-8c823698e12b.png)
