### ISSUE TITLE
Update 'The system is down' web page with new design

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguide-circuit-breaker#151]
Refer to Megan's new 'The system is down' design in the ac-guides-design channel and update our html to look like that.

Updates to check-balance-fail-with-open-circuit.html and check-balance-fail.html.  Can we only have one of these?   Why are there two different ones?

**Comment by kinueng** [comment]
We need SVG from design
![image](https://user-images.githubusercontent.com/31117513/46486015-79739180-c7c2-11e8-9678-c9d5a7887c77.png)
