### ISSUE TITLE
Fewer next buttons at the beginning of the guide

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/iguide-circuit-breaker#16]
Have have fewer next buttons between intro text and the first interactive step 
- could combine What you'll learn, background concepts, example bank scenario into one page, and then clicking on one scrolls you to that point. This approach requires new codes even it still has the title in the TOC.
  + requires a sticky table of contents 
- could use a pattern of using the Next button only to go to next interactive stage

**Comment by steven1046** [comment]
This issue needs design's feedback on having table of content links to subsections on one step, as it would be inconsistent having multiple links to one step and then the rest link to their own step.

**Comment by steven1046** [comment]
The movement of the sections is done, we just need the sticky table of contents.
