### ISSUE TITLE
Performance: loading of svgs

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/iguide-circuit-breaker#17]
Combining all svgs into one call

**Comment by kevinwlau** [comment]
I don't believe this is a good idea as it makes the SVGs harder to maintain.

**Comment by kinueng** [comment]
Look to see what the openliberty.io website handles network traffic for SVG images (ie cache?)

**Comment by kevinwlau** [comment]
As the SVG files are pretty small (few KB each or less), and only a few are loaded at a time on-demand for each step, I believe performance isn't an issue. It is probably better to keep how it is currently and have it easily maintainable.
