### ISSUE TITLE
Image updates and enhancements

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/iguide-circuit-breaker#19]
- [x] the image with processing via the fallback needs to be corrected with the flow going to the fallback service
- [x] open circuit breaker should have an opening (a slanted line) for better illustration
- [x] config/run/play icons and circuit breaker images not consistent with design of openliberty.io
--> Design has indicated that they like the current config/run/play so no action here.

**Comment by lavenal** [comment]
With the latest codes, the image with fallback has been corrected to show the flow going to the fallback service.

**Comment by mbroz2** [comment]
Todo: reach out to design to obtain improved images.

**Comment by mbroz2** [comment]
Play, run, config icons:
![image](https://user-images.githubusercontent.com/3076261/33494314-77f4f474-d688-11e7-8215-0cb4b6995a2c.png)
Used in places like: https://openlibertydev.mybluemix.net/guides/circuit-breaker.html#configuring-the-failure-threshold

Open circuit breaker icon:
![image](https://user-images.githubusercontent.com/3076261/33494407-c5593806-d688-11e7-8d2d-1fd305c95233.png)
![image](https://user-images.githubusercontent.com/3076261/33494492-08f8ef48-d689-11e7-8d69-2f0cb87ddedd.png)
For the open circuit breaker, I would keep the box and just break it in half into two right angled triangles. This would show a physical break in the circuit.

**Comment by mbroz2** [comment]
New Open Circuit image:
![image](https://user-images.githubusercontent.com/3076261/33673687-1cd9cd8c-da73-11e7-9b06-6066ccdc2d95.png)
Design likes the current config/run/play so no action there.

**Comment by kinueng** [comment]
Note: We have the new images from design

**Comment by dmorgant** [comment]
Ask design to change the 'flow' through the wires to look more like a lightning bolt -vs- the shading they currently have.

**Comment by dmorgant** [comment]
Add items in this issue have been completed.   Closing the issue.
