### ISSUE TITLE
Pictures in the fallback steps need to be updated.

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguide-circuit-breaker#199]
The pictures in the fallback steps ('Adding the \@Fallback annotation' and 'Checking the balance with fallback') do not match the text.  They need to be updated.  In the very least, the 'Checking the balance with fallback' step should **NOT** start with an empty pod.

NOTE:  I think new pictures need to be created.

**Comment by aknguyen7** [comment]
We will show half open with fall back pic in the pod to begin with instead of empty pod and then transition to open with fallback pic
