### ISSUE TITLE
Icon is wrong size in IE

### ISSUE THREAD

**Issue by amyreit** [OpenLiberty/iguide-circuit-breaker#225]
The icon on the Configuring Failure Threshold steps that is the Open icon in the pod with the text and the red service oval is cut off on the bottom in IE. We put the margin at 8px 10px but that's what is making it too low in IE.

**Comment by amyreit** [comment]
Probably fixed when Denise delivers the transition code because she has removed the margin.

**Comment by dmorgant** [comment]
With the fix for issue #220 the margins were removed.  We will have to retest once that fix is merged.

**Comment by dmorgant** [comment]
This was fixed by changes for issue #220.
