### ISSUE TITLE
Layout of playground step not good on Safari on Mac

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguide-circuit-breaker#234]
Design feedback on completed CB multipane guide item: 
On the interactive circuit breaker playground step, on Safari on Mac, the result pane layout is messed up.  Works ok on Chrome.

![image](https://user-images.githubusercontent.com/29490139/48789729-50945680-ecb3-11e8-86e2-440d2ed88980.png)

**Comment by cajaygle** [comment]
Fixed for me with the latest code.

**Comment by dmorgant** [comment]
The HTML files are cached.  The html file for the playground step had been updated.  Move to a new tab or browser window if you are experiencing this problem.  Closing the issue.
