### ISSUE TITLE
When editor error 'here' button selected, scroll to code updated

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguide-circuit-breaker#261]
When the editor error 'here' button is selected, the code we are looking for is inserted properly into the file.  User feedback indicates that they would like to see this code that is inserted.  

Update the circuit breaker guide so that we scroll to the code that is inserted, much like processing of the action button that inserts code (see https://github.com/OpenLiberty/iguide-circuit-breaker/pull/260).   

No longer allow focus change to the browser at this point.  By this I mean when code is inserted either by the first instruction of a step or by selecting the 'here' link in the editor error message.  I think this really only applies to the Configure steps.  Focus can change when the user selects the 'Refresh' action button of the 2nd instruction or when they hit the refresh button on the sample browser.

Reported as part of user review: https://ibm.ent.box.com/notes/357464733535?s=xd8grnzempji580yomgw7zm8gwug4c62

**Comment by dmorgant** [comment]
Related issues: 
https://github.com/OpenLiberty/iguide-retry-timeout/issues/123
https://github.com/OpenLiberty/iguide-bulkhead/issues/163

**Comment by aknguyen7** [comment]
We will still focus on the browser, but scroll the editor into view for added text
