### ISSUE TITLE
Add failOn and skipOn parameter support

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/iguide-circuit-breaker#288]
FT 2.1 adds support for failOn and skipOn parameters on @CircuitBreaker and @Fallback.
Update the guide to make use of the parameters on both annotations.  Update the Bulkhead guide to call out failOn and skipOn being covered in the CircuitBreaker guide (aka, "For more information on using the @Fallback annotation to identify a method, see the MicroProfile Circuit Breaker guide." would be updated to something like "For more information on using the @Fallback annotation to identify a method or using the skipOn and failOn parameters, see the MicroProfile Circuit Breaker guide.") 

Fallback:
https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/microprofile-fault-tolerance-spec.html#_specify_the_criteria_for_triggering_fallback

Circuit Breaker:
https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/microprofile-fault-tolerance-spec.html#_configuring_which_exceptions_are_considered_a_failure

**Comment by k8vance88** [comment]
Also, try to upgrade the other server.xml features:
servlet-3.1 <!---- this is at 4.0
cdi-1.2 <!--- This is at 2.0
