### ISSUE TITLE
Default values don't show intuitive behaviour

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/iguide-circuit-breaker#45]
I found the default values of 2 and 0.5 a little counter-intuitive at first because it only requires 1 failure to open the circuit.  This is especially confusing if you first do a "failure" (the circuit remains closed) and then do a "success", and the circuit then opens.  I don't think that example behaviour really sells the concept.  I wondered if the concepts would be easier to understand with values were 3 and 0.5.

**Comment by mbroz2** [comment]
Upping the value from 2 to 3 would force the user to take extra steps that would have no impact (would cause no change).  It would also clutter the instructions with repetitiveness and likely force the user to scroll to the important content.
