### ISSUE TITLE
Reword adding CircuitBreaker policy to be less confusing

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/iguide-circuit-breaker#78]
Based on Laura's feedback at #74 

> Adding the @circuitbreaker annotation: I think this needs a brief explanation of why you’re adding the default @circuitbreaker policy. I don’t follow why we’re doing this at this stage. I know it’s explained more on the next page but I didn’t understand the previous page.

Saying 'default CircuitBreaker policy' may be confusing to the reader. This may be more clear by removing the word 'default', because we later explain each default value if they are not specified.

**Comment by dmorgant** [comment]
Incorporated into feedback issue #74.  Closing this issue as a duplicate.
