### ISSUE TITLE
Update Description for Circuit Breaker so it's not redundant with the title

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/iguide-circuit-breaker#86]
Currently, the Circuit Breaker description mainly reiterates what the title already states:
![image](https://user-images.githubusercontent.com/3076261/35944890-c81a53ba-0c23-11e8-9fd6-9a4deb6df532.png)

We need to update the description so that it further explains what the guide is about and why the user should try it.

**Comment by kinueng** [comment]
@mbroz2 
What would you like for the title and description for this one?

**Comment by mbroz2** [comment]
Title: Preventing repeated failing calls to microservices
Description: Learn how to create a fault tolerent microservice using MicroProfile's CircuitBreaker and Fallback policies
